# Generated by Django 6.0.1 on 2026-01-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.TextField(max_length=50)),
                ('about_description', models.TextField(max_length=250)),
            ],
        ),
    ]
